package findings

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"
	"testing"

	"github.com/traceforce/skill-xray/internal/pytext"
)

// tests/test_findings.py::test_every_referenced_vector_is_registered
// Python walks the AST for SXV-\d+ string constants; here every non-test .go file under
// internal/ and cmd/ is scanned for "SXV-\d+" literals.
func TestEveryReferencedVectorIsRegistered(t *testing.T) {
	literal := regexp.MustCompile(`"(SXV-\d+)"`)
	missing := map[string]bool{}
	for _, dir := range []string{"../../internal", "../../cmd"} {
		err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			src, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			for _, m := range literal.FindAllStringSubmatch(string(src), -1) {
				if _, ok := Vectors[m[1]]; !ok {
					missing[m[1]] = true
				}
			}
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	if len(missing) > 0 {
		t.Errorf("vectors emitted in source but absent from Vectors: %v", missing)
	}
	if len(Vectors) != 44 {
		t.Errorf("registry has %d entries, want 44", len(Vectors))
	}
}

// tests/test_findings.py::test_duplicates_do_not_consume_finding_cap
func TestDuplicatesDoNotConsumeFindingCap(t *testing.T) {
	duplicate := Finding{Vector: "SXV-008", Rule: "taint", Severity: "critical", Path: "run.py", Message: "duplicate", Line: Int(1)}
	unique := Finding{Vector: "SXV-008", Rule: "taint", Severity: "critical", Path: "run.py", Message: "unique", Line: Int(2)}
	var in []Finding
	for range Cap {
		in = append(in, duplicate)
	}
	in = append(in, unique)

	got := CapFindings(in)

	if want := []Finding{duplicate, unique}; !reflect.DeepEqual(got, want) {
		t.Errorf("got %v want %v", got, want)
	}
}

// tests/test_findings.py::test_manifest_capability_classes_are_capped_independently
func TestManifestCapabilityClassesAreCappedIndependently(t *testing.T) {
	var in []Finding
	for index := range Cap + 1 {
		in = append(in, Finding{Vector: "SXV-033", Rule: "manifest-capability-understated", Severity: "medium",
			Path: "run.py", Message: fmt.Sprintf("execution %d", index), Line: Int(index + 1),
			Evidence: map[string]any{"understated_capability": "execution"}})
	}
	network := Finding{Vector: "SXV-033", Rule: "manifest-capability-understated", Severity: "medium",
		Path: "run.py", Message: "network", Line: Int(Cap + 2),
		Evidence: map[string]any{"understated_capability": "network"}}

	got := CapFindings(append(in, network))

	found, capped := false, false
	for _, f := range got {
		found = found || reflect.DeepEqual(f, network)
		capped = capped || f.Rule == "findings-capped" && strings.Contains(f.Message, "execution")
	}
	if !found || !capped {
		t.Errorf("network kept: %v, execution capped: %v", found, capped)
	}
}

type golden struct {
	Inputs []Finding
	ToDict []struct {
		Keys  []string
		Value map[string]any
	} `json:"to_dict"`
	Sorted, Deduped, Capped []Finding
}

func loadGolden(t *testing.T) golden {
	raw, err := os.ReadFile("testdata/golden.json")
	if err != nil {
		t.Fatal(err)
	}
	dec := json.NewDecoder(strings.NewReader(string(raw)))
	dec.UseNumber()
	var g golden
	if err := dec.Decode(&g); err != nil {
		t.Fatal(err)
	}
	for _, fs := range [][]Finding{g.Inputs, g.Sorted, g.Deduped, g.Capped} {
		for i := range fs { // ints inside decoded evidence must be Go int (00-overview D7)
			pytext.Intify(fs[i].Evidence)
		}
	}
	return g
}

// encode renders findings through MarshalJSON so nil and empty evidence compare equal, as in Python.
func encode(t *testing.T, fs []Finding) []string {
	out := make([]string, len(fs))
	for i, f := range fs {
		b, err := json.Marshal(f)
		if err != nil {
			t.Fatal(err)
		}
		out[i] = string(b)
	}
	return out
}

func keysOf(t *testing.T, doc []byte) []string {
	dec := json.NewDecoder(strings.NewReader(string(doc)))
	var keys []string
	if _, err := dec.Token(); err != nil {
		t.Fatal(err)
	}
	for dec.More() {
		tok, err := dec.Token()
		if err != nil {
			t.Fatal(err)
		}
		keys = append(keys, tok.(string))
		if err := dec.Decode(new(any)); err != nil {
			t.Fatal(err)
		}
	}
	return keys
}

// Behaviour goldens generated by testdata/gen_golden.py from skill_xray.findings
// (Finding.to_dict, sort_findings, dedupe_findings, cap_findings) over 110 adversarial inputs.
func TestGolden(t *testing.T) {
	g := loadGolden(t)
	if len(g.Inputs) != 110 {
		t.Fatalf("golden has %d inputs, want 110", len(g.Inputs))
	}
	t.Run("to_dict", func(t *testing.T) {
		for i, f := range g.Inputs {
			doc, err := json.Marshal(f)
			if err != nil {
				t.Fatal(err)
			}
			// numbers compare numerically (00-overview D11): Python spells the one float 3.0, Go 3
			wantDoc, err := json.Marshal(g.ToDict[i].Value)
			if err != nil {
				t.Fatal(err)
			}
			var got, want any
			if err := json.Unmarshal(doc, &got); err != nil {
				t.Fatal(err)
			}
			if err := json.Unmarshal(wantDoc, &want); err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(got, want) {
				t.Errorf("input %d: got %s want %s", i, doc, wantDoc)
			}
			if keys := keysOf(t, doc); !reflect.DeepEqual(keys, g.ToDict[i].Keys) {
				t.Errorf("input %d: key order %v want %v", i, keys, g.ToDict[i].Keys)
			}
			if title := f.ToMap()["title"]; !reflect.DeepEqual(title, g.ToDict[i].Value["title"]) {
				t.Errorf("input %d: ToMap title %v want %v", i, title, g.ToDict[i].Value["title"])
			}
		}
	})
	for _, tc := range []struct {
		name string
		fn   func([]Finding) []Finding
		want []Finding
	}{
		{"sort_findings", Sort, g.Sorted},
		{"dedupe_findings", Dedupe, g.Deduped},
		{"cap_findings", CapFindings, g.Capped},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, want := encode(t, tc.fn(g.Inputs)), encode(t, tc.want)
			if len(got) != len(want) {
				t.Fatalf("got %d findings, want %d", len(got), len(want))
			}
			for i := range got {
				if got[i] != want[i] {
					t.Errorf("row %d:\n got %s\nwant %s", i, got[i], want[i])
				}
			}
		})
	}
	t.Run("findings_to_dicts", func(t *testing.T) {
		maps := ToMaps(g.Inputs)
		for i, f := range g.Sorted {
			if maps[i]["message"] != f.Message || maps[i]["severity"] != f.Severity {
				t.Errorf("row %d: %v vs %v", i, maps[i], f)
			}
		}
	})
	t.Run("inputs_unchanged", func(t *testing.T) {
		fresh := loadGolden(t)
		if !reflect.DeepEqual(encode(t, g.Inputs), encode(t, fresh.Inputs)) {
			t.Error("Sort/Dedupe/CapFindings mutated their input")
		}
	})
}
