package findings

// Vectors maps each SXV id to its title, CWE tags and tier; a finding whose vector is absent
// still reports, without title/cwe/tier enrichment.
var Vectors = map[string]Meta{
	"SXV-001": {Title: "Load-time preprocessing execution via inline dynamic-context injection", CWE: []string{"CWE-94", "CWE-829"}, Tier: "T2"},
	"SXV-002": {Title: "Load-time preprocessing execution via bang-tagged fenced block", CWE: []string{"CWE-94", "CWE-829"}, Tier: "T2"},
	"SXV-003": {Title: "Unresolvable variable substitution inside an execution pre-grant", CWE: []string{"CWE-829", "CWE-732"}, Tier: "T3"},
	"SXV-004": {Title: "Over-broad execution or network pre-grant in allowed-tools", CWE: []string{"CWE-732"}, Tier: "T3"},
	"SXV-005": {Title: "Agent-identity file persistence write with a concealment or priority aggravator", CWE: []string{"CWE-829", "CWE-94"}, Tier: "T2"},
	"SXV-006": {Title: "Startup-hook persistence installation into the agent configuration root", CWE: []string{"CWE-829", "CWE-94"}, Tier: "T2"},
	"SXV-007": {Title: "Instructed concealment of the skill's own actions from the operator", CWE: []string{"CWE-451"}, Tier: "T2"},
	"SXV-008": {Title: "Untrusted-argument command injection with a proven assignment chain", CWE: []string{"CWE-78", "CWE-77"}, Tier: "T1"},
	"SXV-009": {Title: "Unverified remote code execution from a network source", CWE: []string{"CWE-494", "CWE-829"}, Tier: "T2"},
	"SXV-010": {Title: "Staged fetch-then-execute across separate statements", CWE: []string{"CWE-494", "CWE-829"}, Tier: "T2"},
	"SXV-011": {Title: "Credential read directed to network egress in the instruction lane", CWE: []string{"CWE-522", "CWE-200"}, Tier: "T2"},
	"SXV-012": {Title: "Package-root hook auto-execution surface with an unresolvable target", CWE: []string{"CWE-829"}, Tier: "T3"},
	"SXV-013": {Title: "Floating remote package in an auto-start server configuration", CWE: []string{"CWE-1395", "CWE-494"}, Tier: "T3"},
	"SXV-014": {Title: "Hidden-codepoint smuggling", CWE: []string{"CWE-1007", "CWE-94"}, Tier: "T1"},
	"SXV-015": {Title: "Homoglyph or confusable substitution", CWE: []string{"CWE-1007", "CWE-829"}, Tier: "T1"},
	"SXV-016": {Title: "Unpinned or direct-URL dependency", CWE: []string{"CWE-1395", "CWE-937"}, Tier: "T3"},
	"SXV-017": {Title: "Credential committed in the package", CWE: []string{"CWE-798", "CWE-540"}, Tier: "T1"},
	"SXV-018": {Title: "Remote payload fetched and executed by a bundled script", CWE: []string{"CWE-494", "CWE-829"}, Tier: "T2"},
	"SXV-019": {Title: "Encoded payload decoded directly into an interpreter", CWE: []string{"CWE-506"}, Tier: "T2"},
	"SXV-020": {Title: "Executable payload staged on an anonymous file drop", CWE: []string{"CWE-829"}, Tier: "T2"},
	"SXV-021": {Title: "Cloud instance-metadata access from a skill script", CWE: []string{"CWE-918", "CWE-522"}, Tier: "T2"},
	"SXV-022": {Title: "Container or host-escape primitive in a skill script", CWE: []string{"CWE-250"}, Tier: "T2"},
	"SXV-023": {Title: "Private-credential file read in a skill script", CWE: []string{"CWE-522", "CWE-538"}, Tier: "T2"},
	"SXV-024": {Title: "Cloud storage upload sink in a skill script", CWE: []string{"CWE-200"}, Tier: "T3"},
	"SXV-025": {Title: "Home-directory or secret-path enumeration in a skill script", CWE: []string{"CWE-200", "CWE-538"}, Tier: "T2"},
	"SXV-026": {Title: "Whole-environment harvesting in a skill script", CWE: []string{"CWE-526", "CWE-200"}, Tier: "T3"},
	"SXV-027": {Title: "Hidden agent directive inside an HTML comment", CWE: []string{"CWE-506"}, Tier: "T2"},
	"SXV-028": {Title: "Instruction-override or jailbreak directive", CWE: []string{"CWE-77", "CWE-1427"}, Tier: "T2"},
	"SXV-029": {Title: "Anti-refusal or safety-bypass directive", CWE: []string{"CWE-1427"}, Tier: "T3"},
	"SXV-030": {Title: "Cross-session memory-persistence directive", CWE: []string{"CWE-1427"}, Tier: "T3"},
	"SXV-031": {Title: "Covert behavior-manipulation directive", CWE: []string{"CWE-1427"}, Tier: "T2"},
	"SXV-032": {Title: "Cross-agent configuration snooping in a skill script", CWE: []string{"CWE-200", "CWE-497"}, Tier: "T2"},
	"SXV-033": {Title: "Permission understatement: manifest declares less than the code does", CWE: []string{"CWE-280", "CWE-863"}, Tier: "T3"},
	"SXV-034": {Title: "Unsafe YAML deserialisation tag in skill metadata", CWE: []string{"CWE-502", "CWE-94"}, Tier: "T2"},
	"SXV-035": {Title: "File byte-signature contradicts its declared type", CWE: []string{"CWE-646", "CWE-506"}, Tier: "T2"},
	"SXV-036": {Title: "Polyglot file valid as two container formats", CWE: []string{"CWE-506", "CWE-838"}, Tier: "T2"},
	"SXV-037": {Title: "Unreferenced trailing bytes after a container's logical end", CWE: []string{"CWE-506"}, Tier: "T2"},
	"SXV-038": {Title: "Semantic prompt-injection, covert exfiltration, or user-manipulation in skill text (LLM-adjudicated)", CWE: []string{"CWE-1427", "CWE-200"}, Tier: "T2"},
	"SXV-039": {Title: "OS-level persistence write (shell-rc, cron, systemd, autostart) with a remote-execution payload", CWE: []string{"CWE-506", "CWE-829"}, Tier: "T2"},
	"SXV-040": {Title: "Reverse shell / socket-backed interactive shell in a skill script", CWE: []string{"CWE-506", "CWE-912"}, Tier: "T1"},
	"SXV-041": {Title: "Remote instruction loading in the instruction lane (fetch-and-follow / progressive disclosure)", CWE: []string{"CWE-829", "CWE-1427"}, Tier: "T2"},
	"SXV-042": {Title: "Covert bundled-script execution directive (run a shipped script hidden from or forced on the user)", CWE: []string{"CWE-506", "CWE-912", "CWE-1427"}, Tier: "T2"},
	"SXV-043": {Title: "Sensitive-data exfiltration directive (send the user's data to a recipient hard-coded in the skill)", CWE: []string{"CWE-200", "CWE-359", "CWE-1427"}, Tier: "T1"},
	"SXV-044": {Title: "Obfuscated or minified shipped script", CWE: []string{"CWE-506", "CWE-912"}, Tier: "T2"},
}
